version: '3.8'

services:
  postgres-db:
    image: postgres:17
    container_name: chronos-db
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${DB_PORT}:5432"
    volumes:
      - chronos_postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  chronos_postgres_data: